// Curated list of IANA timezone identifiers with friendly display names
const TIMEZONES = [
  // Americas
  { iana: 'America/New_York',       label: 'New York (ET)' },
  { iana: 'America/Chicago',        label: 'Chicago (CT)' },
  { iana: 'America/Denver',         label: 'Denver (MT)' },
  { iana: 'America/Phoenix',        label: 'Phoenix (MST)' },
  { iana: 'America/Los_Angeles',    label: 'Los Angeles (PT)' },
  { iana: 'America/Anchorage',      label: 'Anchorage (AKT)' },
  { iana: 'Pacific/Honolulu',       label: 'Honolulu (HT)' },
  { iana: 'America/Toronto',        label: 'Toronto (ET)' },
  { iana: 'America/Vancouver',      label: 'Vancouver (PT)' },
  { iana: 'America/Mexico_City',    label: 'Mexico City (CT)' },
  { iana: 'America/Sao_Paulo',      label: 'São Paulo (BRT)' },
  { iana: 'America/Argentina/Buenos_Aires', label: 'Buenos Aires (ART)' },
  { iana: 'America/Bogota',         label: 'Bogotá (COT)' },
  { iana: 'America/Lima',           label: 'Lima (PET)' },
  { iana: 'America/Santiago',       label: 'Santiago (CLT)' },
  // Europe
  { iana: 'Europe/London',          label: 'London (GMT/BST)' },
  { iana: 'Europe/Paris',           label: 'Paris (CET)' },
  { iana: 'Europe/Berlin',          label: 'Berlin (CET)' },
  { iana: 'Europe/Madrid',          label: 'Madrid (CET)' },
  { iana: 'Europe/Rome',            label: 'Rome (CET)' },
  { iana: 'Europe/Amsterdam',       label: 'Amsterdam (CET)' },
  { iana: 'Europe/Brussels',        label: 'Brussels (CET)' },
  { iana: 'Europe/Stockholm',       label: 'Stockholm (CET)' },
  { iana: 'Europe/Oslo',            label: 'Oslo (CET)' },
  { iana: 'Europe/Copenhagen',      label: 'Copenhagen (CET)' },
  { iana: 'Europe/Helsinki',        label: 'Helsinki (EET)' },
  { iana: 'Europe/Warsaw',          label: 'Warsaw (CET)' },
  { iana: 'Europe/Prague',          label: 'Prague (CET)' },
  { iana: 'Europe/Vienna',          label: 'Vienna (CET)' },
  { iana: 'Europe/Zurich',          label: 'Zurich (CET)' },
  { iana: 'Europe/Lisbon',          label: 'Lisbon (WET)' },
  { iana: 'Europe/Athens',          label: 'Athens (EET)' },
  { iana: 'Europe/Bucharest',       label: 'Bucharest (EET)' },
  { iana: 'Europe/Kiev',            label: 'Kyiv (EET)' },
  { iana: 'Europe/Moscow',          label: 'Moscow (MSK)' },
  { iana: 'Europe/Istanbul',        label: 'Istanbul (TRT)' },
  // Middle East & Africa
  { iana: 'Asia/Dubai',             label: 'Dubai (GST)' },
  { iana: 'Asia/Riyadh',            label: 'Riyadh (AST)' },
  { iana: 'Asia/Tehran',            label: 'Tehran (IRST)' },
  { iana: 'Africa/Cairo',           label: 'Cairo (EET)' },
  { iana: 'Africa/Nairobi',         label: 'Nairobi (EAT)' },
  { iana: 'Africa/Lagos',           label: 'Lagos (WAT)' },
  { iana: 'Africa/Johannesburg',    label: 'Johannesburg (SAST)' },
  // Asia
  { iana: 'Asia/Kolkata',           label: 'Mumbai / Delhi (IST)' },
  { iana: 'Asia/Dhaka',             label: 'Dhaka (BST)' },
  { iana: 'Asia/Colombo',           label: 'Colombo (SLST)' },
  { iana: 'Asia/Kathmandu',         label: 'Kathmandu (NPT)' },
  { iana: 'Asia/Almaty',            label: 'Almaty (ALMT)' },
  { iana: 'Asia/Tashkent',          label: 'Tashkent (UZT)' },
  { iana: 'Asia/Karachi',           label: 'Karachi (PKT)' },
  { iana: 'Asia/Bangkok',           label: 'Bangkok (ICT)' },
  { iana: 'Asia/Ho_Chi_Minh',       label: 'Ho Chi Minh City (ICT)' },
  { iana: 'Asia/Jakarta',           label: 'Jakarta (WIB)' },
  { iana: 'Asia/Singapore',         label: 'Singapore (SGT)' },
  { iana: 'Asia/Kuala_Lumpur',      label: 'Kuala Lumpur (MYT)' },
  { iana: 'Asia/Manila',            label: 'Manila (PHT)' },
  { iana: 'Asia/Shanghai',          label: 'Shanghai / Beijing (CST)' },
  { iana: 'Asia/Hong_Kong',         label: 'Hong Kong (HKT)' },
  { iana: 'Asia/Taipei',            label: 'Taipei (CST)' },
  { iana: 'Asia/Tokyo',             label: 'Tokyo (JST)' },
  { iana: 'Asia/Seoul',             label: 'Seoul (KST)' },
  { iana: 'Asia/Vladivostok',       label: 'Vladivostok (VLAT)' },
  // Oceania
  { iana: 'Australia/Perth',        label: 'Perth (AWST)' },
  { iana: 'Australia/Darwin',       label: 'Darwin (ACST)' },
  { iana: 'Australia/Adelaide',     label: 'Adelaide (ACST/ACDT)' },
  { iana: 'Australia/Sydney',       label: 'Sydney (AEST/AEDT)' },
  { iana: 'Australia/Melbourne',    label: 'Melbourne (AEST/AEDT)' },
  { iana: 'Australia/Brisbane',     label: 'Brisbane (AEST)' },
  { iana: 'Pacific/Auckland',       label: 'Auckland (NZST/NZDT)' },
  { iana: 'Pacific/Fiji',           label: 'Fiji (FJT)' },
  // UTC
  { iana: 'UTC',                    label: 'UTC' },
];
